### ISSUE TITLE
Float Support

### ISSUE THREAD

**Issue by KoltonG** [homebound-team/truss#16]
Feature note to add `float` support.

```css
.fl { float: left; }
.fr { float: right; }
.fn { float: none; }
```

**Inspiration:** http://tachyons.io/docs/layout/floats/
