### ISSUE TITLE
Support for justifyContent: "space-evenly"

### ISSUE THREAD

**Issue by KoltonG** [homebound-team/truss#19]
Enhancement request for the following property: 

```Css
.justifyEvenly: { justify-content: space-evenly; }
```

**Inspiration**: http://tachyons.io/docs/layout/flexbox/
